# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ticket_pb2 as ticket__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ticket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketServiceStub(object):
    """─── Services ───
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuyTicket = channel.unary_unary(
                '/flashsale.TicketService/BuyTicket',
                request_serializer=ticket__pb2.BuyTicketRequest.SerializeToString,
                response_deserializer=ticket__pb2.BuyTicketResponse.FromString,
                _registered_method=True)
        self.GetTicketCount = channel.unary_unary(
                '/flashsale.TicketService/GetTicketCount',
                request_serializer=ticket__pb2.TicketCountRequest.SerializeToString,
                response_deserializer=ticket__pb2.TicketCountResponse.FromString,
                _registered_method=True)
        self.RequestElection = channel.unary_unary(
                '/flashsale.TicketService/RequestElection',
                request_serializer=ticket__pb2.ElectionRequest.SerializeToString,
                response_deserializer=ticket__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.ForwardBuy = channel.unary_unary(
                '/flashsale.TicketService/ForwardBuy',
                request_serializer=ticket__pb2.ForwardBuyRequest.SerializeToString,
                response_deserializer=ticket__pb2.ForwardBuyResponse.FromString,
                _registered_method=True)
        self.RequestLock = channel.unary_unary(
                '/flashsale.TicketService/RequestLock',
                request_serializer=ticket__pb2.LockRequest.SerializeToString,
                response_deserializer=ticket__pb2.LockResponse.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/flashsale.TicketService/ReleaseLock',
                request_serializer=ticket__pb2.UnlockRequest.SerializeToString,
                response_deserializer=ticket__pb2.UnlockResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/flashsale.TicketService/Heartbeat',
                request_serializer=ticket__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=ticket__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class TicketServiceServicer(object):
    """─── Services ───
    """

    def BuyTicket(self, request, context):
        """Client-facing RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicketCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestElection(self, request, context):
        """Node-to-Node RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardBuy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuyTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyTicket,
                    request_deserializer=ticket__pb2.BuyTicketRequest.FromString,
                    response_serializer=ticket__pb2.BuyTicketResponse.SerializeToString,
            ),
            'GetTicketCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicketCount,
                    request_deserializer=ticket__pb2.TicketCountRequest.FromString,
                    response_serializer=ticket__pb2.TicketCountResponse.SerializeToString,
            ),
            'RequestElection': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestElection,
                    request_deserializer=ticket__pb2.ElectionRequest.FromString,
                    response_serializer=ticket__pb2.ElectionResponse.SerializeToString,
            ),
            'ForwardBuy': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardBuy,
                    request_deserializer=ticket__pb2.ForwardBuyRequest.FromString,
                    response_serializer=ticket__pb2.ForwardBuyResponse.SerializeToString,
            ),
            'RequestLock': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestLock,
                    request_deserializer=ticket__pb2.LockRequest.FromString,
                    response_serializer=ticket__pb2.LockResponse.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=ticket__pb2.UnlockRequest.FromString,
                    response_serializer=ticket__pb2.UnlockResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=ticket__pb2.HeartbeatRequest.FromString,
                    response_serializer=ticket__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flashsale.TicketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flashsale.TicketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketService(object):
    """─── Services ───
    """

    @staticmethod
    def BuyTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/BuyTicket',
            ticket__pb2.BuyTicketRequest.SerializeToString,
            ticket__pb2.BuyTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTicketCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/GetTicketCount',
            ticket__pb2.TicketCountRequest.SerializeToString,
            ticket__pb2.TicketCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/RequestElection',
            ticket__pb2.ElectionRequest.SerializeToString,
            ticket__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardBuy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/ForwardBuy',
            ticket__pb2.ForwardBuyRequest.SerializeToString,
            ticket__pb2.ForwardBuyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/RequestLock',
            ticket__pb2.LockRequest.SerializeToString,
            ticket__pb2.LockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/ReleaseLock',
            ticket__pb2.UnlockRequest.SerializeToString,
            ticket__pb2.UnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashsale.TicketService/Heartbeat',
            ticket__pb2.HeartbeatRequest.SerializeToString,
            ticket__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
